# Generated by Django 4.0.5 on 2022-06-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Categories',
        ),
    ]
